---
# Variable configuration.
- include_tasks: variables.yml
- include_tasks: reset.yml
  when: ansible_os_family == 'Debian' and postgresql_reset | bool

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat' and not postgresql_reset

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian' and not postgresql_reset

- include_tasks: initialize.yml
  when: not postgresql_reset
- include_tasks: configure.yml
  when: not postgresql_reset

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"
  when: not postgresql_reset

# Configure PostgreSQL.
- import_tasks: users.yml
  when: not postgresql_reset
- import_tasks: databases.yml
  when: not postgresql_reset
- import_tasks: users_props.yml
  when: not postgresql_reset
