---
# Variable configuration.
- name: variables
  include_tasks: variables.yml
- name: reset
  include_tasks: reset.yml
  when: ansible_os_family == 'Debian' and postgresql_reset | bool

# Setup/install tasks.
- name: setup-RedHat
  include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat' and not postgresql_reset

- name: setup-Debian
  include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian' and not postgresql_reset

- name: initialize
  include_tasks: initialize.yml
  when: not postgresql_reset
- name: configure
  include_tasks: configure.yml
  when: not postgresql_reset

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"
  when: not postgresql_reset

# Configure PostgreSQL.
- name: users
  import_tasks: users.yml
  when: not postgresql_reset
- name: databases
  import_tasks: databases.yml
  when: not postgresql_reset
- name: users_props
  import_tasks: users_props.yml
  when: not postgresql_reset
