---
# Variable configuration.
- name: variables
  include_tasks: variables.yml


# Setup/install tasks.
- name: setup-RedHat
  include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: setup-Debian
  include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: initialize
  include_tasks: initialize.yml

- name: configure
  include_tasks: configure.yml


- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"


# Configure PostgreSQL.
- name: users
  import_tasks: users.yml

- name: databases
  import_tasks: databases.yml

- name: users_props
  import_tasks: users_props.yml



- name: reset everything
  include_tasks: reset.yml
  when: ansible_os_family == 'Debian' and postgresql_reset | bool
